update pipeline

diff --git a/.github/workflows/pipelineIC.yml b/.github/workflows/pipelineIC.yml
--- a/.github/workflows/pipelineIC.yml
+++ b/.github/workflows/pipelineIC.yml
@@ -43,6 +43,11 @@ jobs:
             curl -X POST -u "${{ secrets.SONAR_TOKEN }}:" 'https://sonarcloud.io/api/project_branches/rename' \
             -d "name=main" \
             -d "project=${{ github.event.repository.name }}"
+            if [ $? -ne 0 ]; then
+              echo "Error al renombrar rama"
+            else
+              echo "Rename exitoso"
+            fi
           fi
 
 
